import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { ArrowUpRight, CheckCircle2, FileText, ImagePlus, LayoutDashboard, Loader2, Pencil, Plus, Save, Trash2, UploadCloud } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type ProgramForm = { id?: number; title: string; category: string; summary: string; status: "draft" | "published"; sortOrder: number };
type UpdateForm = { id?: number; title: string; excerpt: string; body: string; status: "draft" | "published" };
type ContentForm = { contentKey: string; label: string; title: string; body: string; actionLabel: string; actionHref: string };

const blankProgram: ProgramForm = { title: "", category: "", summary: "", status: "draft", sortOrder: 0 };
const blankUpdate: UpdateForm = { title: "", excerpt: "", body: "", status: "draft" };
const blankContent: ContentForm = { contentKey: "", label: "", title: "", body: "", actionLabel: "", actionHref: "" };

function fileToBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result).split(",")[1] ?? "");
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(file);
  });
}

function AdminAccessDenied() {
  const { user, loading } = useAuth();
  if (loading) return <div className="admin-auth-state"><Loader2 className="spin" size={28} /> Loading your access…</div>;
  if (!user) return <div className="admin-auth-state"><p className="admin-kicker">YBI management</p><h1>Sign in to manage the site.</h1><p>Use the account that owns Young Beginners Inspiration to continue.</p><button onClick={() => startLogin()} className="admin-primary">Sign in <ArrowUpRight size={17} /></button></div>;
  if (user.role !== "admin") return <div className="admin-auth-state"><p className="admin-kicker">Access restricted</p><h1>This account is not an administrator.</h1><p>Ask the site owner to promote your account before accessing the management dashboard.</p><a href="/" className="admin-secondary">Return to website</a></div>;
  return <AdminWorkspace />;
}

function AdminWorkspace() {
  const [location] = useLocation();
  const section = location.split("/")[2] || "overview";
  return <DashboardLayout><div className="admin-page"><AdminPageHeader section={section} />{section === "gallery" ? <GalleryManager /> : section === "programs" ? <ProgramsManager /> : section === "updates" ? <UpdatesManager /> : section === "content" ? <ContentManager /> : <Overview />}</div></DashboardLayout>;
}

function AdminPageHeader({ section }: { section: string }) {
  const names: Record<string, string> = { overview: "Dashboard", gallery: "Gallery manager", programs: "Program manager", updates: "Updates manager", content: "Site content" };
  return <div className="admin-page-header"><div><p className="admin-kicker">Young Beginners Inspiration</p><h1>{names[section] || "Dashboard"}</h1></div><a className="admin-public-link" href="/" target="_blank" rel="noreferrer">View public site <ArrowUpRight size={16} /></a></div>;
}

function Overview() {
  const { data, isLoading, isError } = trpc.admin.overview.useQuery();
  const cards = [{ label: "Gallery photos", value: data?.gallery ?? 0, href: "/admin/gallery", icon: ImagePlus, tone: "yellow" }, { label: "Programs", value: data?.programs ?? 0, href: "/admin/programs", icon: LayoutDashboard, tone: "orange" }, { label: "Updates", value: data?.updates ?? 0, href: "/admin/updates", icon: FileText, tone: "red" }, { label: "Content blocks", value: data?.content ?? 0, href: "/admin/content", icon: Pencil, tone: "blue" }];
  return <div className="admin-overview"><div className="admin-welcome"><div><p className="admin-kicker">Your control room</p><h2>Keep every YBI story<br />clear, current, and visible.</h2></div><p>Use this workspace to publish gallery moments, programs, updates, and key public-facing content. Only administrators can make changes.</p></div>{isError ? <div className="admin-error-state">Dashboard data could not be loaded. Refresh the page and try again.</div> : <><div className="admin-metric-grid">{cards.map(({ label, value, href, icon: Icon, tone }) => <a href={href} className="admin-metric-card" key={label}><div className={`admin-metric-icon ${tone}`}><Icon size={21} /></div><span>{label}</span><strong>{isLoading ? "—" : value}</strong><small>Manage <ArrowUpRight size={13} /></small></a>)}</div><div className="admin-next-card"><CheckCircle2 size={24} /><div><h3>Publishing workflow</h3><p>Create content in draft, preview it in the dashboard, then set it to published when it is ready to appear on the public site.</p></div></div></>}</div>;
}

function GalleryManager() {
  const utils = trpc.useUtils();
  const { data: photos, isLoading, isError } = trpc.admin.gallery.list.useQuery();
  const upload = trpc.admin.gallery.upload.useMutation({ onSuccess: () => { utils.admin.gallery.list.invalidate(); utils.admin.overview.invalidate(); utils.publicSite.gallery.invalidate(); toast.success("Photo uploaded and saved to the shared gallery."); }, onError: (error) => toast.error("Photo upload failed.", { description: error.message }) });
  const save = trpc.admin.gallery.save.useMutation({ onSuccess: () => { utils.admin.gallery.list.invalidate(); utils.publicSite.gallery.invalidate(); toast.success("Gallery photo updated."); }, onError: (error) => toast.error("Gallery photo could not be updated.", { description: error.message }) });
  const remove = trpc.admin.gallery.remove.useMutation({ onSuccess: () => { utils.admin.gallery.list.invalidate(); utils.admin.overview.invalidate(); utils.publicSite.gallery.invalidate(); toast.success("Gallery photo removed from the site."); }, onError: (error) => toast.error("Gallery photo could not be removed.", { description: error.message }) });
  const [file, setFile] = useState<File | null>(null);
  const [title, setTitle] = useState("");
  const [altText, setAltText] = useState("");
  const [isPublished, setIsPublished] = useState(true);
  const uploadPhoto = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return toast.error("Choose a JPG, PNG, or WEBP photo first."); if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) return toast.error("Use a JPG, PNG, or WEBP photo."); try { const base64 = await fileToBase64(file); upload.mutate({ title: title || file.name.replace(/\.[^/.]+$/, ""), altText: altText || "Young Beginners Inspiration community moment", fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp", base64, isPublished, sortOrder: (photos?.length ?? 0) + 1 }); setFile(null); setTitle(""); setAltText(""); } catch { toast.error("The image could not be read. Please try again."); } };
  return <div className="admin-manager-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Persistent storage</p><h2>Upload a gallery moment</h2></div><UploadCloud size={25} /></div><form className="admin-form" onSubmit={uploadPhoto}><label>Photo file<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /></label><label>Photo title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Community workshop" /></label><label>Accessible description<input value={altText} onChange={(event) => setAltText(event.target.value)} placeholder="Participants sharing ideas at a YBI workshop" /></label><label className="admin-check"><input type="checkbox" checked={isPublished} onChange={(event) => setIsPublished(event.target.checked)} /> Publish this photo immediately</label><button disabled={upload.isPending} className="admin-primary" type="submit">{upload.isPending ? "Uploading…" : "Upload to shared gallery"} <UploadCloud size={17} /></button></form><p className="admin-help">JPG, PNG, or WEBP only. Photos are stored securely and can be published or hidden later.</p></section><section className="admin-panel admin-list-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Current collection</p><h2>Manage photos</h2></div><span className="admin-count">{photos?.length ?? 0}</span></div>{isLoading ? <div className="admin-empty"><Loader2 className="spin" /> Loading gallery…</div> : isError ? <div className="admin-error-state">Gallery data could not be loaded. Refresh and try again.</div> : !photos?.length ? <div className="admin-empty">No shared photos yet. Upload the first one from this screen.</div> : <div className="admin-photo-list">{photos.map((photo) => <article className="admin-photo-row" key={photo.id}><img src={photo.imageUrl} alt={photo.altText} /><div><h3>{photo.title}</h3><p>{photo.altText}</p><span className={photo.isPublished ? "admin-status published" : "admin-status draft"}>{photo.isPublished ? "Published" : "Hidden"}</span></div><div className="admin-row-actions"><button onClick={() => save.mutate({ id: photo.id, title: photo.title, altText: photo.altText, isPublished: !photo.isPublished, sortOrder: photo.sortOrder })}>{photo.isPublished ? "Hide" : "Publish"}</button><button className="danger" onClick={() => { if (window.confirm(`Remove “${photo.title}” from the gallery?`)) remove.mutate({ id: photo.id }); }}><Trash2 size={15} /></button></div></article>)}</div>}</section></div>;
}

function ProgramsManager() {
  const utils = trpc.useUtils(); const { data: programs, isLoading, isError } = trpc.admin.programs.list.useQuery(); const save = trpc.admin.programs.save.useMutation({ onSuccess: () => { utils.admin.programs.list.invalidate(); utils.admin.overview.invalidate(); toast.success("Program saved."); }, onError: (error) => toast.error("Program could not be saved.", { description: error.message }) }); const remove = trpc.admin.programs.remove.useMutation({ onSuccess: () => { utils.admin.programs.list.invalidate(); utils.admin.overview.invalidate(); toast.success("Program removed."); }, onError: (error) => toast.error("Program could not be removed.", { description: error.message }) }); const [form, setForm] = useState<ProgramForm>(blankProgram); const update = <K extends keyof ProgramForm>(key: K, value: ProgramForm[K]) => setForm(current => ({ ...current, [key]: value })); const submit = (event: React.FormEvent) => { event.preventDefault(); save.mutate(form, { onSuccess: () => setForm(blankProgram) }); };
  return <div className="admin-manager-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Programs</p><h2>{form.id ? "Edit program" : "Add a program"}</h2></div><Plus size={24} /></div><form className="admin-form" onSubmit={submit}><label>Program title<input required value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="Public Speaking" /></label><label>Category<input required value={form.category} onChange={(event) => update("category", event.target.value)} placeholder="Leadership development" /></label><label>Summary<textarea required value={form.summary} onChange={(event) => update("summary", event.target.value)} placeholder="Describe the practical benefit and audience." /></label><div className="admin-form-split"><label>Status<select value={form.status} onChange={(event) => update("status", event.target.value as ProgramForm["status"])}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Order<input type="number" min="0" value={form.sortOrder} onChange={(event) => update("sortOrder", Number(event.target.value))} /></label></div><button disabled={save.isPending} className="admin-primary" type="submit"><Save size={17} /> {form.id ? "Save program" : "Create program"}</button>{form.id ? <button type="button" className="admin-text-button" onClick={() => setForm(blankProgram)}>Cancel editing</button> : null}</form></section>{isError ? <section className="admin-panel admin-error-state">Programs could not be loaded. Refresh and try again.</section> : <RecordsList title="Programs" items={programs ?? []} loading={isLoading} onEdit={(program) => setForm({ id: program.id, title: program.title, category: program.category, summary: program.summary, status: program.status, sortOrder: program.sortOrder })} onRemove={(id, title) => { if (window.confirm(`Remove “${title}”?`)) remove.mutate({ id }); }} />}</div>;
}

function UpdatesManager() {
  const utils = trpc.useUtils(); const { data: updates, isLoading, isError } = trpc.admin.updates.list.useQuery(); const save = trpc.admin.updates.save.useMutation({ onSuccess: () => { utils.admin.updates.list.invalidate(); utils.admin.overview.invalidate(); toast.success("Update saved."); }, onError: (error) => toast.error("Update could not be saved.", { description: error.message }) }); const remove = trpc.admin.updates.remove.useMutation({ onSuccess: () => { utils.admin.updates.list.invalidate(); utils.admin.overview.invalidate(); toast.success("Update removed."); }, onError: (error) => toast.error("Update could not be removed.", { description: error.message }) }); const [form, setForm] = useState<UpdateForm>(blankUpdate); const update = <K extends keyof UpdateForm>(key: K, value: UpdateForm[K]) => setForm(current => ({ ...current, [key]: value })); const submit = (event: React.FormEvent) => { event.preventDefault(); save.mutate(form, { onSuccess: () => setForm(blankUpdate) }); };
  return <div className="admin-manager-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">News & notes</p><h2>{form.id ? "Edit update" : "Create an update"}</h2></div><FileText size={24} /></div><form className="admin-form" onSubmit={submit}><label>Headline<input required value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="Start with the room you are in" /></label><label>Short introduction<textarea required value={form.excerpt} onChange={(event) => update("excerpt", event.target.value)} placeholder="A summary for update listings." /></label><label>Full text<textarea className="admin-tall-textarea" required value={form.body} onChange={(event) => update("body", event.target.value)} placeholder="Write the full update here." /></label><label>Status<select value={form.status} onChange={(event) => update("status", event.target.value as UpdateForm["status"])}><option value="draft">Draft</option><option value="published">Published</option></select></label><button disabled={save.isPending} className="admin-primary" type="submit"><Save size={17} /> {form.id ? "Save update" : "Publish update"}</button>{form.id ? <button type="button" className="admin-text-button" onClick={() => setForm(blankUpdate)}>Cancel editing</button> : null}</form></section>{isError ? <section className="admin-panel admin-error-state">Updates could not be loaded. Refresh and try again.</section> : <RecordsList title="Updates" items={updates ?? []} loading={isLoading} onEdit={(item) => setForm({ id: item.id, title: item.title, excerpt: item.excerpt, body: item.body, status: item.status })} onRemove={(id, title) => { if (window.confirm(`Remove “${title}”?`)) remove.mutate({ id }); }} />}</div>;
}

function RecordsList({ title, items, loading, onEdit, onRemove }: { title: string; items: Array<{ id: number; title: string; summary?: string; excerpt?: string; status: "draft" | "published" }>; loading: boolean; onEdit: (item: any) => void; onRemove: (id: number, title: string) => void; }) {
  return <section className="admin-panel admin-list-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Saved records</p><h2>{title}</h2></div><span className="admin-count">{items.length}</span></div>{loading ? <div className="admin-empty"><Loader2 className="spin" /> Loading…</div> : !items.length ? <div className="admin-empty">Nothing has been created yet.</div> : <div className="admin-record-list">{items.map((item) => <article className="admin-record-row" key={item.id}><div><span className={`admin-status ${item.status}`}>{item.status}</span><h3>{item.title}</h3><p>{item.summary ?? item.excerpt}</p></div><div className="admin-row-actions"><button onClick={() => onEdit(item)}><Pencil size={15} /> Edit</button><button className="danger" onClick={() => onRemove(item.id, item.title)}><Trash2 size={15} /></button></div></article>)}</div>}</section>;
}

function ContentManager() {
  const utils = trpc.useUtils(); const { data: blocks, isLoading, isError } = trpc.admin.content.list.useQuery(); const save = trpc.admin.content.save.useMutation({ onSuccess: () => { utils.admin.content.list.invalidate(); utils.publicSite.content.invalidate(); toast.success("Site content saved."); }, onError: (error) => toast.error("Site content could not be saved.", { description: error.message }) }); const [form, setForm] = useState<ContentForm>(blankContent); const update = <K extends keyof ContentForm>(key: K, value: ContentForm[K]) => setForm(current => ({ ...current, [key]: value })); const submit = (event: React.FormEvent) => { event.preventDefault(); save.mutate({ ...form, actionLabel: form.actionLabel || null, actionHref: form.actionHref || null }); };
  const preparedBlocks = useMemo(() => [{ contentKey: "homepage-hero", label: "Homepage hero", title: "Inspiring voices,\nbuilding leaders,\nshaping futures.", body: "We create a platform where the young and the aged inspire one another, build practical capability, and use their gifts to make a positive difference in the world.", actionLabel: "Support us", actionHref: "/join-us" }, ...(blocks ?? [])], [blocks]);
  return <div className="admin-manager-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Public website</p><h2>{form.contentKey ? "Edit content block" : "Add content block"}</h2></div><Pencil size={24} /></div><form className="admin-form" onSubmit={submit}><label>Content key<input required value={form.contentKey} onChange={(event) => update("contentKey", event.target.value)} placeholder="homepage-hero" /></label><label>Admin label<input required value={form.label} onChange={(event) => update("label", event.target.value)} placeholder="Homepage hero" /></label><label>Heading<textarea required value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="Use line breaks if needed." /></label><label>Body<textarea className="admin-tall-textarea" required value={form.body} onChange={(event) => update("body", event.target.value)} placeholder="Write the public-facing copy." /></label><div className="admin-form-split"><label>Button label<input value={form.actionLabel} onChange={(event) => update("actionLabel", event.target.value)} placeholder="Support us" /></label><label>Button destination<input value={form.actionHref} onChange={(event) => update("actionHref", event.target.value)} placeholder="/join-us" /></label></div><button disabled={save.isPending} className="admin-primary" type="submit"><Save size={17} /> Save content</button></form></section><section className="admin-panel admin-list-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Available blocks</p><h2>Site content</h2></div><span className="admin-count">{blocks?.length ?? 0}</span></div>{isLoading ? <div className="admin-empty"><Loader2 className="spin" /> Loading…</div> : isError ? <div className="admin-error-state">Site content could not be loaded. Refresh and try again.</div> : <div className="admin-record-list">{preparedBlocks.map((block) => <article className="admin-record-row" key={block.contentKey}><div><span className="admin-status published">{block.contentKey}</span><h3>{block.label}</h3><p>{block.body}</p></div><div className="admin-row-actions"><button onClick={() => setForm({ contentKey: block.contentKey, label: block.label, title: block.title, body: block.body, actionLabel: block.actionLabel ?? "", actionHref: block.actionHref ?? "" })}><Pencil size={15} /> Edit</button></div></article>)}</div>}</section></div>;
}

export default function AdminDashboard() { return <AdminAccessDenied />; }
